export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_START = 'GET_GAMES_START';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL'
export const SET_GAMES = 'SET_GAMES';
export const SORT_BY = 'SORT_BY';
export const RATING_ID_REMOVE = 'RATING_ID_REMOVE';
export const RATING_ID_PUSH = 'RATING_ID_PUSH';
export const INCREASE_RATING = 'INCREASE_RATING';
export const DECREASE_RATING = 'DECREASE_RATING';

export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_GAME = 'GET_GAME';
export const GET_GAME_START = 'GET_GAME_START';
export const GET_GAME_FAIL = 'GET_GAME_FAIL'
export const SET_GAME = 'SET_GAME';

export const ADD_GAME = 'ADD_GAME';
export const ADD_GAME_START = 'ADD_GAME_START';
export const ADD_GAME_FAIL = 'ADD_GAME_FAIL';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';

export const SET_GAME_START = 'SET_GAME_START';
export const SET_GAME_SUCCESS = 'SET_GAME_SUCCESS';
export const SET_GAME_FAIL = 'SET_GAME_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_START = 'SIGN_UP_START';
export const SIGNUP_FAIL = 'SIGN_UP_FAIL';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const GET_NEW_TOKEN = 'GET_NEW_TOKEN';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_DATA_START = 'SET_USER_DATA_START';
export const SET_USER_DATA_FAIL = 'SET_USER_DATA_FAIL';
export const SET_USER_DATA_SUCCESS = 'SET_USER_DATA_SUCCESS';

export const GET_AUTHOR_DATA = 'GET_AUTHOR_DATA';
export const GET_AUTHOR_DATA_START = 'GET_AUTHOR_START';
export const GET_AUTHOR_DATA_FAIL = 'GET_AUTHOR_START';
export const SET_AUTHOR_DATA = 'GET_AUTHOR_START';

export const GET_GAMES_BY_AUTHOR = 'GET_GAMES_BY_AUTHOR';
export const GET_GAMES_BY_AUTHOR_START = 'GET_GAMES_BY_AUTHOR_START';
export const GET_GAMES_BY_AUTHOR_FAIL = 'GET_GAMES_BY_AUTHOR_FAIL';
export const SET_GAMES_BY_AUTHOR = 'SET_GAMES_BY_AUTHOR';

